version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - .data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
  web:
    build: .
    command: sh -c "cd main && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"

    ports:
      - "8001:8001"
    env_file:
      - ./.env
    depends_on:
      - db
