# Generated by Django 5.0.4 on 2024-05-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_product_options_order_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default=None, upload_to="products/%Y/%m/%d"
            ),
        ),
    ]
